# Generated by Django 3.1 on 2023-05-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Жас')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Жас',
                'verbose_name_plural': 'Жас',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonName', models.CharField(max_length=255, verbose_name='Мезгіл атауы')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Мезгіл',
                'verbose_name_plural': 'Мезгілдер',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weatherName', models.CharField(max_length=255, verbose_name='Ауа-райы')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Ауа-райы',
                'verbose_name_plural': 'Ауа-райы',
            },
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Лук атауы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сипаттамасы')),
                ('head', models.ImageField(blank=True, null=True, upload_to='images/heads/', verbose_name='Головной убор')),
                ('headLink', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сілтеме')),
                ('eyes', models.ImageField(blank=True, null=True, upload_to='images/eyes/', verbose_name='Көз')),
                ('eyesLink', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сілтеме')),
                ('top1', models.ImageField(blank=True, null=True, upload_to='images/top1/', verbose_name='Куртка')),
                ('top1Link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сілтеме')),
                ('top2', models.ImageField(blank=True, null=True, upload_to='images/top2/', verbose_name='Футболка')),
                ('top2Link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сілтеме')),
                ('hands', models.ImageField(blank=True, null=True, upload_to='images/hands/', verbose_name='Қол')),
                ('handsLink', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сілтеме')),
                ('bottom1', models.ImageField(blank=True, null=True, upload_to='images/bottom1/', verbose_name='Шалбар')),
                ('bottom1Link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сілтеме')),
                ('bottom2', models.ImageField(blank=True, null=True, upload_to='images/bottom2/', verbose_name='Шолақ')),
                ('bottom2Link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сілтеме')),
                ('shoes', models.ImageField(blank=True, null=True, upload_to='images/shoes/', verbose_name='Аяқ киім')),
                ('shoesLink', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сілтеме')),
                ('isFavorite', models.BooleanField(blank=True, default=False, null=True, verbose_name='Таңдаулы')),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warderobApp.age', verbose_name='Жас')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warderobApp.season', verbose_name='Мезгіл')),
                ('weather', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warderobApp.weather', verbose_name='Ауа-райы')),
            ],
            options={
                'verbose_name': 'Лук',
                'verbose_name_plural': 'Луктар',
            },
        ),
    ]
