# Generated by Django 3.1 on 2023-05-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warderobApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стиль')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стиль',
            },
        ),
        migrations.AddField(
            model_name='look',
            name='lookFullPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/looks/', verbose_name='Луктың суреті'),
        ),
        migrations.AlterField(
            model_name='look',
            name='head',
            field=models.ImageField(blank=True, null=True, upload_to='images/heads/', verbose_name='Бас киім'),
        ),
        migrations.AddField(
            model_name='look',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warderobApp.style', verbose_name='Стиль'),
        ),
    ]
