# Generated by Django 3.1 on 2023-05-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warderobApp', '0002_auto_20230508_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='look',
            name='bottom1',
            field=models.ImageField(blank=True, null=True, upload_to='bottom1/', verbose_name='Шалбар'),
        ),
        migrations.AlterField(
            model_name='look',
            name='bottom2',
            field=models.ImageField(blank=True, null=True, upload_to='bottom2/', verbose_name='Шолақ'),
        ),
        migrations.AlterField(
            model_name='look',
            name='eyes',
            field=models.ImageField(blank=True, null=True, upload_to='eyes/', verbose_name='Көз'),
        ),
        migrations.AlterField(
            model_name='look',
            name='hands',
            field=models.ImageField(blank=True, null=True, upload_to='hands/', verbose_name='Қол'),
        ),
        migrations.AlterField(
            model_name='look',
            name='head',
            field=models.ImageField(blank=True, null=True, upload_to='heads/', verbose_name='Бас киім'),
        ),
        migrations.AlterField(
            model_name='look',
            name='lookFullPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='looks/', verbose_name='Луктың суреті'),
        ),
        migrations.AlterField(
            model_name='look',
            name='shoes',
            field=models.ImageField(blank=True, null=True, upload_to='shoes/', verbose_name='Аяқ киім'),
        ),
        migrations.AlterField(
            model_name='look',
            name='top1',
            field=models.ImageField(blank=True, null=True, upload_to='top1/', verbose_name='Куртка'),
        ),
        migrations.AlterField(
            model_name='look',
            name='top2',
            field=models.ImageField(blank=True, null=True, upload_to='top2/', verbose_name='Футболка'),
        ),
    ]
