# Generated by Django 4.2.1 on 2023-05-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warderobApp', '0005_alter_age_id_alter_look_id_alter_season_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='isPopular',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Таңымал'),
        ),
    ]
